services:
  demo-hello-builder-3.18:
    image: hello-builder:3.18
    container_name: demo-hello-builder-3.18
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/workspace:/workspace
    working_dir: /workspace
    command: sleep infinity
    labels:
      - "builder.type=hello"
      - "builder.version=linux"
      - "builder.status=ready"

  demo-rust-builder-1.88:
    image: rust-builder:1.88-bullseye
    container_name: demo-rust-builder-1.88
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/demo-rust-builder-1.88/registry:/root/.cargo/registry
      - ./volumes/cache/demo-rust-builder-1.88/git:/root/.cargo/git
      - ./volumes/cache/demo-rust-builder-1.88/bin:/root/.cargo/bin
    working_dir: /workspace
    labels:
      - "builder.type=rust"
      - "builder.version=1.88"
      - "builder.status=ready"

  demo-go-builder-1.24:
    image: go-builder:1.24-alpine
    container_name: demo-go-builder-1.24
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/workspace:/workspace
    working_dir: /workspace
    labels:
      - "builder.type=golang"
      - "builder.version=1.24"
      - "builder.status=ready"

volumes:
  demo-rust-cache-1.88:
  demo-hello-cache-3.18:
  demo-go-cache-1.24:
  # node-cache-22:
  # tauri-cache-latest-cargo:
  # tauri-cache-latest-npm:
