services:
  hello-builder-3.18:
    image: hello-builder:3.18
    container_name: hello-builder-3.18
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: sleep infinity
    labels:
      - "builder.type=hello"
      - "builder.version=linux"
      - "builder.status=ready"

  rust-builder-1.88:
    image: rust-builder:1.88-alpine
    container_name: rust-builder-1.88
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    labels:
      - "builder.type=rust"
      - "builder.version=1.88"
      - "builder.status=ready"

  go-builder-1.24:
    image: go-builder:1.24-alpine
    container_name: go-builder-1.24
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    labels:
      - "builder.type=golang"
      - "builder.version=1.24"
      - "builder.status=ready"

volumes:
  rust-cache-1.88:
  hello-cache-3.18:
  go-cache-1.24:
  # node-cache-22:
  # tauri-cache-latest-cargo:
  # tauri-cache-latest-npm:
